// export const UPDATE_CF_STATUS = "UPDATE_CF_STATUS";
export const UPDATE_CF_COUNT = 'UPDATE_CF_COUNT';
export const SUBMIT_CONFIRMED = 'SUBMIT_CONFIRMED';
export const SET_CONFIRMED = 'SET_CONFIRMED';
